### ISSUE TITLE
Improve Jenkins CI testing

### ISSUE THREAD

**Issue by tobeycarman** [uaf-arctic-eco-modeling/dvm-dos-tem#110]
We should move "execute shell" commands from the Jenkins web interface (http://jenkins2.snap.uaf.edu/job/dvm-dos-tem-devel/configure) into some sort of `test_script.sh` file that we can keep with the repository and version control. 

Now that the calibration viewer supports static plot generation, we can add more commands that will run in calibration mode and generate a few plots.

**Comment by rarutter** [comment]
Jenkins is no longer used and we have no plans to use it.
