### ISSUE TITLE
Fix Jenkins build.

### ISSUE THREAD

**Issue by tobeycarman** [uaf-arctic-eco-modeling/dvm-dos-tem#208]
Seems like an issue with the restart template files.

Bigger picture, there are two things that probably need to be done:
1. put all the Jenkins configuration/testing stuff into a script so it can be version controlled
2. add to the Jenkins tests code so that we can evaluate more than just the most recently run stage. This might require modifying `dvmdostem` so that it can preserve `.json` outputs between stages.

**Comment by tobeycarman** [comment]
Hmm, looks like we need to figure out how to get python's `netCDF4` installed on Jenkins to be able to create the restart template files...

**Comment by tobeycarman** [comment]
OK, got the basic Jenkins build working again. Outputs can be found here (if you are on the UA network or connected to one of the UA VPNs):

http://jenkins2.snap.uaf.edu/job/dvm-dos-tem-devel/ws/auto-post-process/devel-f45c956/

Still need to work on some of the bigger picture Jenkins organization...

**Comment by rarutter** [comment]
Jenkins is no longer used and we have no plans to use it.
