### ISSUE TITLE
fix Jenkins build.

### ISSUE THREAD

**Issue by tobeycarman** [uaf-arctic-eco-modeling/dvm-dos-tem#363]
Jenkins has `g++ '(GCC)' 4.4.7 20120313 '(Red' Hat '4.4.7-18)' ` which does not support `-std=c++11`. Someday we should address this somehow.

**Comment by rarutter** [comment]
Is this issue still relevant?

**Comment by rarutter** [comment]
Jenkins is no longer used and we have no plans to use it.
