### ISSUE TITLE
enable all variables in output_spec.csv

### ISSUE THREAD

**Issue by Elchin** [uaf-arctic-eco-modeling/dvm-dos-tem#537]
It would be nice to have a command that turns all the variables in the output_spec.csv on.

**Comment by rarutter** [comment]
Would all outputs available by year being output by year be sufficient? There are a few (driving data, qdrainlayer, etc) that are only available daily, but I don't think those are what you're looking for.

**Comment by rarutter** [comment]
I'll likely address #574 first, because the excessive number of errors the script produces when you mess with by-layer outputs makes it hard to test the changes needed for this issue.

**Comment by Elchin** [comment]
yes, enabling all yearly outputs should work.
