### ISSUE TITLE
Forest initial fibric and humic soil thickness values appear high.

### ISSUE THREAD

**Issue by tobeycarman** [uaf-arctic-eco-modeling/dvm-dos-tem#538]
@amullen01 asks on slack:

> Why are "initfibthick" and "inithumthick" so high for the forested community types? For example initfibthick=5.4578 (m) and inithumthick=10.9156 (m)  for the black spruce community type.

He then discovered that the papers from which the values are set ( Melvin et al. 2015, Ruess et al. 1996) give the values in centimeters.

**Comment by tobeycarman** [comment]
Confirming that `dvmdostem` expects the values in m (and not cm):

Looks like the values are read from parameter files into `CohortLookup::initfibthick` and `inithumthick`. 
 * Then these are used to set the `Organic::shlwthick` data members. 
 * `Ground::intiLayerStructure(..)` has a comment indicating that the values should be in meters
<img width="697" alt="image" src="https://user-images.githubusercontent.com/838735/216725930-ce57355c-2a20-44dc-807e-acc45f548c25.png">

*  `Ground::initParameter(..)` also has a comment indicating meters, although it is not immediately clear the distinction between `soildimpar.minshlwthick` and `Organic::shlwthick`
<img width="556" alt="image" src="https://user-images.githubusercontent.com/838735/216726276-09a48ecb-3798-4a15-9f8a-ecb8087e102e.png">

**Comment by amullen01** [comment]
@tobeycarman good to know. Maybe `soildimpar.minshlwthick` the minimum possible shallow organic layer thickness whereas `Organic::shlwthick` is the initial shallow organic layer thickness defined in the parameter file?
