### ISSUE TITLE
Unable to build docker images after new release

### ISSUE THREAD

**Issue by Benjamin-Maglio** [uaf-arctic-eco-modeling/dvm-dos-tem#582]
I updated to the new dvm-dos-tem release last week, and have had a few issues getting docker up and running again. I have updated my .env and docker-compose.yml files appropriately:

```
DDT_INPUT_CATALOG=/home/bmaglio/develop/ddt_inputs
DDT_WORKFLOWS=/home/bmaglio/develop/ddt_outputs
V_TAG=v0.6.2
```

Initially, I was able to build the images but received the following error in the compose up stage:

failed to solve: cpp-dev:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

(which seemed like a problem with the V_TAG, although I am pretty sure this was correctly input in the .env). Anyway, I tried several times with some slight changes, and then deleted the images and ran $docker system prune, and reinstalled docker. Following this I have encountered a new error during the building stage:

```
$ docker build --build-arg GIT_VERSION=0.6.2 --target cpp-dev --tag cpp-dev:0.6.2 .
[+] Building 0.5s (3/3) FINISHED                                                                                      
 => [internal] load build definition from Dockerfile                                                             0.2s
 => => transferring dockerfile: 14.10kB                                                                          0.0s
 => [internal] load .dockerignore                                                                                0.3s
 => => transferring context: 164B                                                                                0.0s
 => ERROR [internal] load metadata for docker.io/library/ubuntu:focal                                            0.2s
------
 > [internal] load metadata for docker.io/library/ubuntu:focal:
------
Dockerfile:42
--------------------
  40 |     # === IMAGE FOR GENERAL C++ DEVELOPMENT =======================================
  41 |     # General development tools, compilers, text editors, etc
  42 | >>> FROM ubuntu:focal as cpp-dev
  43 |     ENV DEBIAN_FRONTEND=noninteractive
  44 |     RUN apt-get update -y --fix-missing && apt-get install -y \
--------------------
ERROR: failed to solve: error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``
```

I'll try a double check my docker install in case I changed anything important.

**Comment by Benjamin-Maglio** [comment]
Update:
Images built. Apparently a wrong entry in ~/.docker/config.json was created during this last installation. Fixed by changing:
"credsStore"  : "desktop" to "credStore" : "desktop"

Now back to the original error on compose up:

$ docker compose up -d cpp-dev
[+] Running 1/1
 ! cpp-dev Warning                                                         3.9s 
[+] Building 0.4s (5/5) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 14.10kB                                    0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 164B                                          0.0s
 => CANCELED [internal] load metadata for docker.io/library/ubuntu:focal   0.3s
 => ERROR [internal] load metadata for docker.io/library/cpp-dev:latest    0.3s
 => CANCELED [internal] load metadata for docker.io/library/dvmdostem-dev  0.3s
------
 > [internal] load metadata for docker.io/library/cpp-dev:latest:
------
failed to solve: cpp-dev:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by hgenet** [comment]
Thanks Ben, and good luck with fixing the rest of the error.
---
Hélène GENET, Ph.D.

Assistant Professor
Institute of Arctic Biology
University of Alaska Fairbanks

A: Arctic Health Research Building, Room 128, 
Koyukuk Drive, Fairbanks AK 99775, USA 
C: +1 (907) 699 4340
E: ***@***.***

**Comment by tobeycarman** [comment]
For example after doing the above experiment, I end up in a situation where `docker compose up -d` hangs up and I have to cancel it (Ctrl-C):
```
$ docker compose up -d      
[+] Running 4/6
 ⠿ Network dvm-dos-tem_default                        Created                                                                                                                                                        0.1s
 ⠏ Container dvm-dos-tem-dvmdostem-dev-1              Creating                                                                                                                                                      26.9s
 ⠿ Container dvm-dos-tem-dvmdostem-build-1            Created                                                                                                                                                        0.1s
 ⠿ Container dvm-dos-tem-cpp-dev-1                    Created                                                                                                                                                        0.1s
 ⠿ Container dvm-dos-tem-dvmdostem-run-1              Created                                                                                                                                                        0.2s
 ⠏ Container dvm-dos-tem-dvmdostem-mapping-support-1  Creating                                                                                                                                                      26.9s
canceled
```
Then `docker compose down` also fails:
```
$ docker compose down 
[+] Running 3/0
 ⠿ Container dvm-dos-tem-cpp-dev-1                    Removed                                                                                                                                                        0.0s
 ⠿ Container dvm-dos-tem-dvmdostem-build-1            Removed                                                                                                                                                        0.0s
 ⠿ Container dvm-dos-tem-dvmdostem-run-1              Removed                                                                                                                                                        0.0s
 ⠿ Container dvm-dos-tem-dvmdostem-mapping-support-1  Error while Stopping                                                                                                                                           0.0s
 ⠿ Container dvm-dos-tem-dvmdostem-dev-1              Error while Stopping                                                                                                                                           0.0s
Error response from daemon: No such container: 0bb825ef4fec0443ca8c68554be906aeebde03bb9e5decf8d568d7ce6ac9715b
```
My solution here is to restart the docker daemon. For Mac this is done via the desktop Dashboard thing, on Linux, I think there is a command line way to do it (`service docker restart`??)

**Comment by Benjamin-Maglio** [comment]
I see. Starting to have a play around now. One thing though is I notice your TAG after `docker image ls` has a v, whereas mine does not:
`$ docker image ls`
`REPOSITORY      TAG       IMAGE ID       CREATED         SIZE`
`dvmdostem-dev   0.6.2     e44318de4d25   6 hours ago     2.89GB`
`cpp-dev         0.6.2     92d9e777c897   6 hours ago     698MB`

Do you think that's a problem?

**Comment by tobeycarman** [comment]
Oh yeah that’ll do it. The docker-build-wrapper.sh script should be tagging
the images with the ‘v’ prefix. Then the setting in the .env file allows
you to keep multiple versions of the images around and start containers
from them.

**Comment by Benjamin-Maglio** [comment]
Oh great. Yeah I think the last time I built the images I did it manually, and had a problem if I included the `v` in `v0.6....`

**Comment by tobeycarman** [comment]
Excellent. I wonder why the `v` causes problems manually?

If your next builds work, I think we can close this issue.

**Comment by hgenet** [comment]
Strange - I remember successfully changing the version manually in the past. 
---
Hélène GENET, Ph.D.

Assistant Professor
Institute of Arctic Biology
University of Alaska Fairbanks

A: Arctic Health Research Building, Room 128, 
Koyukuk Drive, Fairbanks AK 99775, USA 
C: +1 (907) 699 4340
E: ***@***.***

**Comment by Benjamin-Maglio** [comment]
Yeah I think we can close it.
Hmm not sure. If I have some time I may look back through the notes on the
windows machine and see.
