### ISSUE TITLE
Unrecognized Argument in Sensitivity analysis

### ISSUE THREAD

**Issue by valeriabriones** [uaf-arctic-eco-modeling/dvm-dos-tem#678]
After updating the repo, I attempted to run a sensitivity analysis and encountered a new error:
'SA_setup_and_run.py: error: unrecognized arguments: /data/workflows/newtest2/output/initial_params_run_dir'

It seems somewhere in the setup, the initial_params_run_dir is being created and not recognized when running setup_multi which causes the run to fail. All subdirectories are being created, but fails before creating sample folders due to this error. Can't seem to find where exactly the creation of the folder is being called and unrecognized

**Comment by tobeycarman** [comment]
Fixed with 2d8e1e5 (straggling changes that should have been committed with 8f21898cd98).
